backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "faq"
    label: "FAQ"
    folder: "content/faq"
    create: true
    slug: "index"
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: text
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home
        file: content/home.yml
        media_library:
          folder_support: true
        fields:
          - name: title
            label: Title
            widget: string
          - name: intro
            label: Intro
            widget: text
      - name: settings
        label: Settings
        file: content/settings.yml
        fields:
          - name: contact_email
            label: Primary Contact Email
            widget: string
