backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# local_backend: true

collections:
  - name: retreats
    label: Retreats
    extension: yml
    format: yaml
    folder: "content/retreats"
    create: true
    path: "{{title}}"
    editor:
      preview: false
    media_library:
      folder_support: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: intro
        label: Intro
        widget: text
      - name: start_date
        label: Start date
        date_format: "dd/MM/yyyy"
        time_format: false
        widget: datetime
      - name: end_date
        label: End date
        date_format: "dd/MM/yyyy"
        time_format: false
        widget: datetime
      - name: contact_email
        label: Contact email
        widget: string
      - name: hero_image
        label: Hero Image
        widget: image
      - name: program
        label: Program
        widget: object
        required: false
        fields:
          - name: introduction
            label: Introduction
            widget: markdown
          - name: goals
            label: Goals
            widget: markdown
          - name: pricing
            label: Pricing
            widget: markdown
          - name: cancellation_policy
            label: Cancellation
            widget: markdown
          - name: accommodation_details
            label: Accommodation details
            widget: markdown
          - name: facilities
            label: Facilities
            widget: markdown
          - name: accommodation_photo
            label: Accommodation photo
            widget: image
          - name: location
            label: Location
            widget: markdown
          - name: travel
            label: Travel
            widget: markdown
          - name: trainers_intro
            label: Trainers intro
            widget: text
          - name: trainers
            label: Trainers
            widget: relation
            multiple: true
            required: false
            collection: team
            display_fields:
              - title
            search_fields:
              - title
            value_field: user_id
          - name: organisers
            label: Organisers
            widget: relation
            multiple: true
            required: false
            collection: team
            display_fields:
              - title
            search_fields:
              - title
            value_field: user_id
      - name: seo
        label: SEO
        widget: object
        required: false
        fields:
          - name: seo_title
            label: SEO Title
            widget: string
          - name: seo_description
            label: SEO description
            widget: text
          - name: seo_image
            label: SEO Image
            widget: image
      - name: registration
        label: Registration
        widget: object
        required: false
        fields:
          - name: text
            label: Registration form text
            widget: text
          - name: terms_url
            label: Terms and conditions link
            widget: string
      - name: tiers
        label: Pricing tiers
        widget: list
        fields:
          - name: title
            label: Title
            widget: string
            hint: "Name for the pricing tier (e.g: Early bird)"
          - name: price
            label: Price
            widget: string
          - name: parity_price
            label: Parity Price
            widget: string
          - name: start_date
            label: Date
            widget: datetime
            date_format: "dd/MM/yyyy"
            time_format: false
            hint: "Date from which this tier starts"
          - name: end_date
            label: Date
            widget: datetime
            date_format: "dd/MM/yyyy"
            time_format: false
            hint: "Date until which this tier is valid"
      - name: sliding_scale
        label: Sliding scale
        widget: object
        required: false
        fields:
          - name: intro
            label: Intro
            widget: text
          - name: min
            label: Minimum price
            widget: string
          - name: max
            label: Maximum price
            widget: string
          - name: step
            label: Step
            widget: number
      - name: scholarship_info
        label: Scholarship Information
        widget: markdown
      - name: payment_options
        label: Payment options
        widget: object
        required: false
        fields:
          - name: bank_transfer
            title: Direct Bank transfer information
            widget: text
            hint: Should contain bank account details
          - name: mobile_money_transfer
            title: Mobile money transfer
            widget: text

  - name: team
    label: Team
    extension: yml
    format: yaml
    folder: "content/team"
    create: true
    path: "{{title}}"
    editor:
      preview: false
    fields:
      - name: title
        label: Title
        widget: string
      - name: role
        label: Role
        widget: string
        required: false
      - name: bio
        label: Bio
        widget: markdown
      - name: photo
        label: Photo
        widget: image
      - name: user_id
        label: ID
        widget: uuid
        hint: "Do not edit this field"
