backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# local_backend: true

collections:
  - name: retreats
    label: Retreats
    extension: yml
    format: yaml
    folder: "content/retreats"
    create: true
    path: "{{title}}"
    editor:
      preview: false
    media_library:
      folder_support: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: intro
        label: Intro
        widget: text
      - name: start_date
        label: Start date
        widget: datetime
      - name: end_date
        label: End date
        widget: datetime
      - name: contact_email
        label: Contact email
        widget: string
      - name: hero_image
        label: Hero Image
        widget: image
      - name: program
        label: Program
        widget: object
        required: false
        fields:
          - name: introduction
            label: Introduction
            widget: markdown
          - name: details
            label: Details
            widget: markdown
          - name: goals
            label: Goals
            widget: markdown
          - name: pricing
            label: Pricing
            widget: markdown
          - name: cancellation_policy
            label: Cancellation
            widget: markdown
          - name: accommodation_details
            label: Accommodation details
            widget: markdown
          - name: facilities
            label: Facilities
            widget: markdown
          - name: accommodation_photo
            label: Accommodation photo
            widget: image
          - name: location
            label: Location
            widget: markdown
          - name: travel
            label: Travel
            widget: markdown
          - name: trainers
            label: Trainers
            widget: relation
            multiple: true
            required: false
            collection: team
            display_fields:
              - title
            search_fields:
              - title
            value_field: title
          - name: organisers
            label: Organisers
            widget: relation
            multiple: true
            required: false
            collection: team
            display_fields:
              - title
            search_fields:
              - title
            value_field: title

  - name: team
    label: Team
    extension: yml
    format: yaml
    folder: "content/team"
    create: true
    path: "{{title}}"
    editor:
      preview: false
    fields:
      - name: title
        label: Title
        widget: string
      - name: role
        label: Role
        widget: string
      - name: bio
        label: Bio
        widget: markdown
      - name: photo
        label: Photo
        widget: image
